#!/usr/bin/env bash
set -euo pipefail

# Public FFmpeg headers for every libavcodec major the agent knows how to talk
# to, laid out one tree per major:
#
#   <prefix>/58/libavcodec/*.h  <prefix>/58/libavutil/*.h  <prefix>/58/libavfilter/*.h
#   <prefix>/59/...             <prefix>/60/...   <prefix>/61/...
#
# Why this exists: GPU encoding dlopen's libavcodec at runtime, but the struct
# layouts it reads come from the headers it was compiled against, and FFmpeg
# rearranges them on every soname bump. A binary built against one major is
# therefore software-only on every host that ships a different one - which,
# built against the FFmpeg a stable base image happens to have, is most modern
# distributions. Compiling the encoder once per major and picking the matching
# one at runtime is what makes the released packages work everywhere.
#
# Only headers are taken. Nothing is linked, nothing is redistributed, and no
# FFmpeg binary reaches the package or the user's host.
#
# The tarballs are the plain .tar.gz releases so no image needs xz, and the
# major each one carries is verified after extraction rather than trusted -
# a wrong pin here would otherwise produce a silently duplicated ABI.

PREFIX="${1:-/opt/directgate/ffmpeg-headers}"
BASE_URL="${FFMPEG_RELEASE_URL:-https://ffmpeg.org/releases}"
DOWNLOAD_ATTEMPTS="${FFMPEG_DOWNLOAD_ATTEMPTS:-4}"

# <libavcodec major>:<FFmpeg release>. Covers Debian 11/12/13, Ubuntu
# 20.04-24.04, EL8 (RPM Fusion), EL9 and current Fedora, plus the FFmpeg 8
# generation the rolling distributions are moving to. Add a line when a new
# major reaches the distributions and a matching pair of #if blocks to
# src/agent/desktop/hwenc_abi.c; nothing else has to change.
FFMPEG_RELEASES="${FFMPEG_RELEASES:-
58:4.4.4
59:5.1.4
60:6.1.1
61:7.1
62:8.0
}"

log() { printf '[ffmpeg-headers] %s\n' "$*"; }
die() { printf '[ffmpeg-headers] %s\n' "$*" >&2; exit 1; }

# FFmpeg's configure writes libavutil/avconfig.h; a source tarball has no such
# file. Both macros are facts about the target the compiler already knows, so
# derive them instead of hardcoding a guess that would be wrong on a big-endian
# or strict-alignment build.
write_avconfig() {
    cat > "$1/libavutil/avconfig.h" <<'EOF'
/* Generated by misc/ffmpeg-headers.sh - FFmpeg's configure normally emits this
   file. Both values are properties of the target, taken from the compiler. */
#ifndef AVUTIL_AVCONFIG_H
#define AVUTIL_AVCONFIG_H

#if defined(__BYTE_ORDER__) && defined(__ORDER_BIG_ENDIAN__) && \
    __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
#define AV_HAVE_BIGENDIAN 1
#else
#define AV_HAVE_BIGENDIAN 0
#endif

#if defined(__i386__) || defined(__x86_64__) || defined(__aarch64__) || \
    defined(__ARM_FEATURE_UNALIGNED)
#define AV_HAVE_FAST_UNALIGNED 1
#else
#define AV_HAVE_FAST_UNALIGNED 0
#endif

#endif /* AVUTIL_AVCONFIG_H */
EOF
}

# The major moved from version.h to version_major.h in FFmpeg 5, so look in
# both rather than assuming either.
extracted_major() {
    local dest="$1" file value
    for file in "$dest/libavcodec/version_major.h" "$dest/libavcodec/version.h"; do
        [ -f "$file" ] || continue
        value="$(sed -n 's/^#define LIBAVCODEC_VERSION_MAJOR[[:space:]]\+\([0-9]\+\).*/\1/p' "$file")"
        [ -n "$value" ] && { printf '%s\n' "$value"; return 0; }
    done

    return 1
}

fetch_one() {
    local major="$1" release="$2"
    local dest="$PREFIX/$major"
    local url="$BASE_URL/ffmpeg-$release.tar.gz"
    local tmp found attempt

    tmp="$(mktemp -d)"
    trap 'rm -rf "$tmp"' RETURN

    # Retried in the shell rather than with --retry-all-errors, which only
    # exists from curl 7.71 and would leave the oldest build image (EL8, curl
    # 7.61) retrying nothing: a reset connection to a release mirror reports
    # exit 35, which plain --retry does not consider transient. This runs in
    # CI on every push and must not turn a busy mirror into a failed build.
    log "fetching FFmpeg $release for libavcodec $major"

    attempt=1
    until curl -fsSL --retry 3 --retry-delay 2 "$url" -o "$tmp/ffmpeg.tar.gz"; do
        [ "$attempt" -lt "$DOWNLOAD_ATTEMPTS" ] ||
            die "download failed after $attempt attempts: $url"

        log "attempt $attempt failed, retrying in $((attempt * 5))s"
        sleep "$((attempt * 5))"
        attempt=$((attempt + 1))
    done

    # libavfilter comes along because Wayland zero-copy needs the GPU
    # post-processor (scale_vaapi), which is the only place FFmpeg exposes it.
    tar -xzf "$tmp/ffmpeg.tar.gz" -C "$tmp" \
        "ffmpeg-$release/libavcodec" "ffmpeg-$release/libavutil" "ffmpeg-$release/libavfilter" ||
        die "archive does not contain the expected header directories: $url"

    rm -rf "$dest"
    install -d "$dest/libavcodec" "$dest/libavutil" "$dest/libavfilter"
    cp "$tmp/ffmpeg-$release/libavcodec/"*.h "$dest/libavcodec/"
    cp "$tmp/ffmpeg-$release/libavutil/"*.h "$dest/libavutil/"
    cp "$tmp/ffmpeg-$release/libavfilter/"*.h "$dest/libavfilter/"
    write_avconfig "$dest"

    [ -f "$dest/libavcodec/avcodec.h" ] || die "libavcodec/avcodec.h missing from $url"
    [ -f "$dest/libavutil/avutil.h" ] || die "libavutil/avutil.h missing from $url"
    [ -f "$dest/libavfilter/avfilter.h" ] || die "libavfilter/avfilter.h missing from $url"

    found="$(extracted_major "$dest")" || die "cannot read LIBAVCODEC_VERSION_MAJOR from $release"
    [ "$found" = "$major" ] ||
        die "FFmpeg $release carries libavcodec $found, not $major - fix the pin in this script"

    log "libavcodec $major ready in $dest"
}

command -v curl >/dev/null 2>&1 || die "curl is required"
command -v tar >/dev/null 2>&1 || die "tar is required"

install -d "$PREFIX"

for entry in $FFMPEG_RELEASES; do
    fetch_one "${entry%%:*}" "${entry##*:}"
done

log "header trees installed under $PREFIX: $(ls "$PREFIX" | tr '\n' ' ')"
